[versions]
geyser = "2.11.0-SNAPSHOT"
fastutil = "8.5.15"
lombok = "1.18.36"
guava = "33.6.0-jre"
gson = "2.3.1"
jackson = "2.15.2"
shadow = "9.3.0"
minotaur = "2.+"
indra = "4.0.0"
protocol = "3.0.0.Beta12-SNAPSHOT"
mcprotocollib = "1.21.11-20260217.182735-13"
annotations = "26.1.0"

[libraries]
geyser-api = { module = "org.geysermc.geyser:api", version.ref = "geyser" }
geyser-core = { module = "org.geysermc.geyser:core", version.ref = "geyser" }
fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jackson-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
protocol = { module = "org.cloudburstmc.protocol:bedrock-connection", version.ref = "protocol" }
mcprotocollib = { module = "org.geysermc.mcprotocollib:protocol", version.ref = "mcprotocollib" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
indra = { id = "net.kyori.indra", version.ref = "indra" }
indra-publishing = { id = "net.kyori.indra.publishing", version.ref = "indra" }
